import java.awt.Font;
import java.math.BigDecimal;
import java.util.EmptyStackException;

/**
 *
 * The majority of the following code was generated using NetBeans
 *
 * @author Shane Vance
 */

@SuppressWarnings("serial")
public class Client extends javax.swing.JFrame {

	/**
     * Creates new form calculator1
     */
	
	private String textField = "";
	
    public Client() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

    	this.setTitle("Calculator");
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        setResizable(false);

        jButton1.setText("←");
        jButton1.setMaximumSize(new java.awt.Dimension(45, 23));
        jButton1.setMinimumSize(new java.awt.Dimension(45, 23));
        jButton1.setPreferredSize(new java.awt.Dimension(45, 23));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("^");
        jButton2.setMaximumSize(new java.awt.Dimension(45, 23));
        jButton2.setMinimumSize(new java.awt.Dimension(45, 23));
        jButton2.setPreferredSize(new java.awt.Dimension(45, 23));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("C");
        jButton3.setMaximumSize(new java.awt.Dimension(45, 23));
        jButton3.setMinimumSize(new java.awt.Dimension(45, 23));
        jButton3.setPreferredSize(new java.awt.Dimension(45, 23));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("+");
        jButton5.setMaximumSize(new java.awt.Dimension(45, 23));
        jButton5.setMinimumSize(new java.awt.Dimension(45, 23));
        jButton5.setPreferredSize(new java.awt.Dimension(45, 23));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("8");
        jButton6.setMaximumSize(new java.awt.Dimension(45, 23));
        jButton6.setMinimumSize(new java.awt.Dimension(45, 23));
        jButton6.setPreferredSize(new java.awt.Dimension(45, 23));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("7");
        jButton7.setMaximumSize(new java.awt.Dimension(45, 23));
        jButton7.setMinimumSize(new java.awt.Dimension(45, 23));
        jButton7.setPreferredSize(new java.awt.Dimension(45, 23));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("9");
        jButton8.setMaximumSize(new java.awt.Dimension(45, 23));
        jButton8.setMinimumSize(new java.awt.Dimension(45, 23));
        jButton8.setPreferredSize(new java.awt.Dimension(45, 23));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("-");
        jButton9.setMaximumSize(new java.awt.Dimension(45, 23));
        jButton9.setMinimumSize(new java.awt.Dimension(45, 23));
        jButton9.setPreferredSize(new java.awt.Dimension(45, 23));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("4");
        jButton10.setMaximumSize(new java.awt.Dimension(45, 23));
        jButton10.setMinimumSize(new java.awt.Dimension(45, 23));
        jButton10.setPreferredSize(new java.awt.Dimension(45, 23));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("5");
        jButton11.setMaximumSize(new java.awt.Dimension(45, 23));
        jButton11.setMinimumSize(new java.awt.Dimension(45, 23));
        jButton11.setPreferredSize(new java.awt.Dimension(45, 23));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton13.setText("6");
        jButton13.setMaximumSize(new java.awt.Dimension(45, 23));
        jButton13.setMinimumSize(new java.awt.Dimension(45, 23));
        jButton13.setPreferredSize(new java.awt.Dimension(45, 23));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("*");
        jButton14.setMaximumSize(new java.awt.Dimension(45, 23));
        jButton14.setMinimumSize(new java.awt.Dimension(45, 23));
        jButton14.setPreferredSize(new java.awt.Dimension(45, 23));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("2");
        jButton15.setMaximumSize(new java.awt.Dimension(45, 23));
        jButton15.setMinimumSize(new java.awt.Dimension(45, 23));
        jButton15.setPreferredSize(new java.awt.Dimension(45, 23));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setText("3");
        jButton16.setMaximumSize(new java.awt.Dimension(45, 23));
        jButton16.setMinimumSize(new java.awt.Dimension(45, 23));
        jButton16.setPreferredSize(new java.awt.Dimension(45, 23));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setText("1");
        jButton17.setMaximumSize(new java.awt.Dimension(45, 23));
        jButton17.setMinimumSize(new java.awt.Dimension(45, 23));
        jButton17.setPreferredSize(new java.awt.Dimension(45, 23));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setText("/");
        jButton18.setMaximumSize(new java.awt.Dimension(45, 23));
        jButton18.setMinimumSize(new java.awt.Dimension(45, 23));
        jButton18.setPreferredSize(new java.awt.Dimension(45, 23));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton19.setText(".");
        jButton19.setMaximumSize(new java.awt.Dimension(45, 23));
        jButton19.setMinimumSize(new java.awt.Dimension(45, 23));
        jButton19.setPreferredSize(new java.awt.Dimension(45, 23));
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButton20.setText("(");
        jButton20.setMaximumSize(new java.awt.Dimension(45, 23));
        jButton20.setMinimumSize(new java.awt.Dimension(45, 23));
        jButton20.setPreferredSize(new java.awt.Dimension(45, 23));
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jButton21.setText("0");
        jButton21.setMaximumSize(new java.awt.Dimension(45, 23));
        jButton21.setMinimumSize(new java.awt.Dimension(45, 23));
        jButton21.setPreferredSize(new java.awt.Dimension(45, 23));
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jButton22.setText(")");
        jButton22.setMaximumSize(new java.awt.Dimension(45, 23));
        jButton22.setMinimumSize(new java.awt.Dimension(45, 23));
        jButton22.setPreferredSize(new java.awt.Dimension(45, 23));
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        jButton24.setText("=");
        jButton24.setMaximumSize(new java.awt.Dimension(45, 23));
        jButton24.setMinimumSize(new java.awt.Dimension(45, 23));
        jButton24.setPreferredSize(new java.awt.Dimension(45, 23));
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });        
        
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
		jTextField1.setFont(new Font(Font.SANS_SERIF, Font.BOLD, 30));

        jButton25.setToolTipText("");
        jButton25.setMaximumSize(new java.awt.Dimension(45, 23));
        jButton25.setMinimumSize(new java.awt.Dimension(45, 23));
        jButton25.setPreferredSize(new java.awt.Dimension(45, 23));
        jButton25.setEnabled(false);

        jButton26.setToolTipText("");
        jButton26.setMaximumSize(new java.awt.Dimension(45, 23));
        jButton26.setMinimumSize(new java.awt.Dimension(45, 23));
        jButton26.setPreferredSize(new java.awt.Dimension(45, 23));
        jButton26.setEnabled(false);

        jButton27.setToolTipText("");
        jButton27.setMaximumSize(new java.awt.Dimension(45, 23));
        jButton27.setMinimumSize(new java.awt.Dimension(45, 23));
        jButton27.setPreferredSize(new java.awt.Dimension(45, 23));
        jButton27.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(74, 74, 74)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    
    }                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         

    	if (textField.length() > 0) { 
	    	
    		textField = textField.substring(0, textField.length() - 1);
	    	jTextField1.setText(textField);
    	
    	}
    	
    }  
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         

    	textField += "^";
    	jTextField1.setText(textField);
    
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       
    	textField = "";
    	jTextField1.setText(textField);
    	
    }                                             

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         

    	textField += "+";
    	jTextField1.setText(textField);
    	
    }                                        

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         

    	textField += "8";
    	jTextField1.setText(textField);
    	
    }                                        

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	
    	textField += "7";
    	jTextField1.setText(textField);
    	
    }                                        

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         

    	textField += "9";
    	jTextField1.setText(textField);
    	
    }                                        

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
    	textField += "-";
    	jTextField1.setText(textField);
    	
    }                                        

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        
    	textField += "4";
    	jTextField1.setText(textField);
    	
    }                                         

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {                                          
    
    	textField += "5";
    	jTextField1.setText(textField);
    	
    }                                                                               

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {                                          

    	textField += "6";
    	jTextField1.setText(textField);
    	
    }                                         

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {                                          

    	textField += "*";
    	jTextField1.setText(textField);
    	
    }                                         

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {                                          

    	textField += "2";
    	jTextField1.setText(textField);
    	
    }                                         

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {                                          

    	textField += "3";
    	jTextField1.setText(textField);
    	
    }                                         

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {                                          
    	
    	textField += "1";
    	jTextField1.setText(textField);
    	
    }                                         

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        
    	textField += "/";
    	jTextField1.setText(textField);
    	
    }                                         

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {                                          

    	textField += ".";
    	jTextField1.setText(textField);
    	
    }                                         

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {                                          

    	textField += "(";
    	jTextField1.setText(textField);
    	
    }                                         

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        
    	textField += "0";
    	jTextField1.setText(textField);
    	
    }                                         

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {                                          

    	textField += ")";
    	jTextField1.setText(textField);
    	
    }                                         

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {                                          
    
    	String exp = jTextField1.getText();

    	try {
		
    		exp = Calculator.convertToProperExpression(exp);

    	} catch (IndexOutOfBoundsException e) {
			
			jTextField1.setText(e.getMessage());
			
		}
		
		if (Calculator.isEquation(exp)) {

			try {
	
				BigDecimal result = Calculator.eval(exp);
				jTextField1.setText(result.toString());
	
			} catch (NumberFormatException e) {

				jTextField1.setText("Error: invalid input");

			} catch (EmptyStackException e) {

				jTextField1.setText("Error: invalid input");

			} catch (UnsupportedOperationException e) {
	
				jTextField1.setText(e.getMessage());
	
			} catch (ArithmeticException e) {
	
				jTextField1.setText(e.getMessage());

			} catch (ArrayIndexOutOfBoundsException e) {
					
				jTextField1.setText("Error: invalid input");
				
			} catch (IndexOutOfBoundsException e) {
				
				jTextField1.setText("Error: invalid input");
				
			}

		} else if (exp.length() == 0) {

			jTextField1.setText("Nothing to evaluate");

		} else {
	
			jTextField1.setText("Error: invalid input");

		}
			
		
		
    }                                                                                                                      

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration                   
}